raw_data:
  base_directory: '/mnt/z/recordings/Mea1k/leejih/'
  # base_directory: '/net/bs-filesvr02/export/group/hierlemann/recordings/Mea1k/leejih/'
  file_extension: '.h5'

nCPUs: 20

file_index: 0

tablename: 'features'
