raw_data:
  base_directory: '/cluster/scratch/leejih/'
  file_name_pattern: ''
  file_extension: '.h5'

nCPUs: 20

file_index: 0

tablename: 
  FP: 'fp_features'
  AP: 'ap_features'
  FP_AP: 'fp_ap_features'
