raw_data:
#  base_directory: '/mnt/z/recordings/Mea1k/leejih/'
  base_directory: '/net/bs-filesvr02/export/group/hierlemann/recordings/Mea1k/leejih/'
  # base_directory: '/cluster/scratch/leejih/'
  file_name_pattern: ''
  file_extension: '.h5'

nCPUs: 20

file_index: 0

tablename: 
  FP: 'fp_features'
  AP: 'ap_features'

